version: '3'
services:
  bienebot:
    image: hackupc-bienebot
    container_name: hackupc-bienebot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './logs:/srv/biene-bot/logs'
    restart: always